/**
 * The admin panel's contract.
 *
 * Signing in to `apps/admin` is deliberately unlike signing in to the product:
 * it is a username and a password, there is no self-registration, and every
 * account is created by another admin. The two flows share nothing but the
 * envelope — see `auth.ts` for the product's passwordless flow.
 *
 * `apps/admin` and `apps/api` both compile against the definitions below, so a
 * change here is a change both sides see. What only the backend needs — the
 * password hash, attempt counters, session tokens — stays in
 * the `admin-auth` and `admin-users` modules in `apps/api`.
 */

// ─── Roles and permissions ───────────────────────────────────────────────────

/**
 * What an admin is allowed to do. One string per action the backend guards.
 *
 * The UI hides a menu it has no permission for, but that is cosmetic: every
 * route re-checks the same permission server-side, so a hidden menu is not a
 * security boundary and was never treated as one.
 */
export type AdminPermission =
  | 'dashboard.view'
  | 'users.view'
  | 'users.create'
  | 'users.edit'
  | 'users.reset_password'
  | 'forms.view'
  | 'forms.create'
  | 'forms.edit'
  | 'forms.publish'
  | 'forms.delete'
  | 'forms.responses.view'
  | 'forms.responses.export';

/**
 * The roles that exist today. The catalogue itself — which permissions each
 * role carries — lives in `@hamdastan/shared/rbac`, so the front-end and the
 * backend read one list.
 *
 * A role is referenced by this code rather than by a database id, which is what
 * lets the catalogue move into a table later without any stored row changing.
 */
export type AdminRoleCode =
  | 'super_admin'
  | 'user_manager'
  | 'form_manager'
  | 'support';

export type AdminRole = {
  code: AdminRoleCode;
  /** Persian, shown in the UI. */
  name: string;
  permissions: readonly AdminPermission[];
};

// ─── The admin user ──────────────────────────────────────────────────────────

export type AdminAccountStatus = 'ACTIVE' | 'SUSPENDED';

/** An admin account as the panel lists it. Never carries a password of any kind. */
export type AdminUser = {
  id: string;
  firstName: string;
  lastName: string;
  /** Joined once here so every screen shows the same name. */
  fullName: string;
  /** Unique, case-insensitive. What they type to sign in. */
  username: string;
  /** Normalised to `09xxxxxxxxx`. Where credentials are sent. */
  mobile: string;
  roleCode: AdminRoleCode;
  /** Resolved from the catalogue, so a table cell needs no lookup. */
  roleName: string;
  status: AdminAccountStatus;
  /** ISO calendar date, `YYYY-MM-DD`. Access lasts to the end of this day. */
  accessExpiresAt: string;
  /** Decided by the backend, which is the only clock that matters. */
  accessExpired: boolean;
  /** True while the account is still on a temporary password. */
  mustChangePassword: boolean;
  /** ISO timestamp, or null if they have never signed in. */
  lastLoginAt: string | null;
  /** ISO timestamp of the last successful password change, or null. */
  passwordChangedAt: string | null;
  createdAt: string;
};

/**
 * The signed-in admin, as `apps/admin` sees themselves.
 *
 * `permissions` is resolved from the role by the backend and sent down so the
 * shell can hide what the user cannot reach.
 */
export type AdminPrincipal = AdminUser & {
  permissions: readonly AdminPermission[];
};

// ─── Requests and responses ──────────────────────────────────────────────────

export type AdminLoginRequest = { username: string; password: string };

/**
 * A session now exists; the token travels in an httpOnly cookie, not here.
 *
 * `admin.mustChangePassword` is what the panel routes on: true means the only
 * screen they may see is the change-password form.
 */
export type AdminLoginResponse = { admin: AdminPrincipal };

export type AdminSessionResponse = { admin: AdminPrincipal };

export type AdminChangePasswordRequest = {
  newPassword: string;
  confirmPassword: string;
};

export type AdminChangePasswordResponse = { admin: AdminPrincipal };

export type CreateAdminUserRequest = {
  firstName: string;
  lastName: string;
  username: string;
  mobile: string;
  roleCode: AdminRoleCode;
  /** ISO calendar date, `YYYY-MM-DD`. */
  accessExpiresAt: string;
};

/**
 * What creating an account gives back.
 *
 * The temporary password is generated by the backend and sent to the new admin
 * by SMS. `temporaryPassword` is echoed here **only** outside production and
 * only when `SHOW_DEV_CREDENTIALS` is on, because there is no SMS gateway yet —
 * production cannot enable it. Once it is gone it is gone: there is no endpoint
 * that reveals or re-sends an existing password, only one that replaces it.
 */
export type CreateAdminUserResponse = {
  user: AdminUser;
  /** Development only. Never set when `NODE_ENV=production`. */
  temporaryPassword?: string;
  /** Whether the SMS provider accepted the credentials message. */
  smsDelivered: boolean;
};

export type UpdateAdminUserRequest = Partial<{
  firstName: string;
  lastName: string;
  mobile: string;
  roleCode: AdminRoleCode;
  /** ISO calendar date, `YYYY-MM-DD`. */
  accessExpiresAt: string;
  status: AdminAccountStatus;
}>;

export type UpdateAdminUserResponse = { user: AdminUser };

/** Same shape as creating an account, for the same reason. */
export type ResetAdminPasswordResponse = CreateAdminUserResponse;

export type AdminUsersQuery = {
  /** Matches name, username or mobile. */
  search?: string;
  page?: number;
  pageSize?: number;
};

// ─── Errors ──────────────────────────────────────────────────────────────────

/**
 * The `code` on an `ApiFailure` from the admin routes.
 *
 * The panel switches on these — whether to show a field error, send the user to
 * the change-password screen, or say that their access has run out — never on
 * the message text.
 */
export type AdminErrorCode =
  | 'ADMIN_INVALID_CREDENTIALS'
  | 'ADMIN_ACCOUNT_SUSPENDED'
  | 'ADMIN_ACCESS_EXPIRED'
  | 'ADMIN_PASSWORD_CHANGE_REQUIRED'
  | 'ADMIN_TEMPORARY_PASSWORD_EXPIRED'
  | 'ADMIN_TOO_MANY_ATTEMPTS'
  | 'ADMIN_USERNAME_TAKEN'
  | 'ADMIN_FORBIDDEN';
