stages:
  - build
  - deploy

include:
  - component: $CI_SERVER_FQDN/infrastructure/pipeline-components/image-building-components/docker-build@3
    inputs:
      job_suffix: image
      dockerfile: Dockerfile

  - component: $CI_SERVER_FQDN/infrastructure/pipeline-components/deployment-components/helm-tag-trigger@3
    inputs:
      cluster: de_cluster
      namespace: standalone-services
      service: hamdastan
