stages:
  - build
  - deploy

include:
  - component: $CI_SERVER_FQDN/infrastructure/pipeline-components/image-building-components/docker-build@3
    inputs:
      job_suffix: image
      dockerfile: Dockerfile
    #   build_args: >
    #     VITE_API_BASE_URL=https://api.partodata.com

  - component: $CI_SERVER_FQDN/infrastructure/pipeline-components/deployment-components/helm-tag-trigger@3
    inputs:
      cluster: de_cluster
      namespace: standalone-services
      service: {{SERVICE_NAME}}