
version: '3'

services:
  web:
    container_name: {{PROJECT_NAME}}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
